os: osx
addons:
  hosts:
  - authomatic.test
  - authomatic.com
  - authomatic.org
install:
- sudo pip install tox
script:
- sudo tox -e py3 -- -vvx --tb=no
after_failure:
- tail -n 500 tests/functional_tests/*.log
- tail -n 500 tests/*.log
- tail -n 500 flask.log
before_install:
- openssl aes-256-cbc -K $encrypted_a51a72b5b8ba_key -iv $encrypted_a51a72b5b8ba_iv
  -in ./tests/functional_tests/config.py.enc -out ./tests/functional_tests/config.py
  -d
- brew update
- brew cask install google-chrome
